import { createFileRoute, Link } from "@tanstack/react-router";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { MoneyInput } from "@/components/money-input";
import { CadastroCustos } from "@/components/custos-cadastro";
import { useLocalState, brl } from "@/lib/storage";
import * as C from "@/lib/custos";
export const Route = createFileRoute('/custos')({head:()=>({meta:[{title:'Configuração de Custos — Lucrando com Papel'},{name:'description',content:'Materiais, máquinas, ferramentas, rateio e desperdício do seu ateliê.'},{property:'og:title',content:'Configuração de Custos — Lucrando com Papel'},{property:'og:description',content:'Configure os custos reais da produção.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:CustosPage});
const resultado=(c:C.Calc)=>c.valor===null?c.motivo || 'Sem configuração':brl(c.valor);
function CustosPage(){
 const [materiais]=useLocalState<C.MaterialCusto[]>(C.K_MATERIAIS,[]);
 const [maquinas,setMaquinas]=useLocalState<C.Maquina[]>(C.K_MAQUINAS,[]);
 const [ferramentas,setFerramentas]=useLocalState<C.Ferramenta[]>(C.K_FERRAMENTAS,[]);
 const [indiretos,setIndiretos]=useLocalState<C.CustoIndireto[]>(C.K_INDIRETOS,[]);
 const [rateio,setRateio]=useLocalState<C.RateioCfg>(C.K_RATEIO,C.RATEIO_PADRAO);
 const [desperdicio,setDesperdicio]=useLocalState<C.DesperdicioCfg>(C.K_DESPERDICIO,C.DESPERDICIO_PADRAO);
 const [gastos]=useLocalState<{id:string;nome:string;valor:string}[]>('lcp:precif:gastos',[]);
 const [hora]=useLocalState<number>('lcp:valorHora',0);
 const fixos=gastos.reduce((s,g)=>s+(Number(g.valor.replace(',','.'))||0),0);
 return <div className="mx-auto max-w-5xl space-y-6"><PageHeader title="Configuração de Custos" description="Custos reais da produção do seu ateliê"/><Tabs defaultValue="materiais"><TabsList className="flex h-auto flex-wrap justify-start gap-1">{['materiais','embalagens','máquinas','ferramentas','indiretos','rateio','desperdício','mão de obra'].map(t=><TabsTrigger key={t} value={t} className="capitalize">{t}</TabsTrigger>)}</TabsList>
 {['materiais','embalagens'].map(t=><TabsContent key={t} value={t} className="space-y-4"><Button asChild variant="outline"><Link to="/materiais">Cadastrar / editar {t}</Link></Button>{materiais.filter(m=>(m.categoria==='embalagem')===(t==='embalagens')).map(m=><div key={m.id} className="border-b border-border py-3"><p className="font-medium">{m.nome}</p><p className="text-sm text-muted-foreground">{C.custoUnitario(m).valor===null?'Sem custo configurado':`${C.custoUnitario(m).valor?.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:4})} R$ / ${C.labelUnidade(m.unidade)}`} · Estoque: {m.estoque}</p></div>)}{!materiais.some(m=>(m.categoria==='embalagem')===(t==='embalagens')) && <p className="text-muted-foreground">Nenhum cadastro nesta categoria.</p>}</TabsContent>)}
 <TabsContent value="máquinas"><p className="my-4 text-sm text-muted-foreground">Depreciação é o desgaste financeiro da máquina ao longo do tempo. Para 5 anos, informe 60 meses.</p><CadastroCustos titulo="Máquinas e equipamentos" registros={maquinas} salvar={setMaquinas} novo={()=>({id:crypto.randomUUID(),nome:'',tipo:'',valorAquisicao:0,valorResidual:0,vidaUnidade:'meses',vidaUtil:0,horasMes:0,manutencaoMensal:0,ativo:true})} campos={[{key:'nome',label:'Nome'},{key:'tipo',label:'Tipo'},{key:'valorAquisicao',label:'Valor de aquisição (R$)',tipo:'numero'},{key:'valorResidual',label:'Valor residual (R$)',tipo:'numero'},{key:'dataAquisicao',label:'Data de aquisição',tipo:'data'},{key:'vidaUnidade',label:'Vida útil em',opcoes:[['meses','Meses'],['horas','Horas de uso']]},{key:'vidaUtil',label:'Vida útil',tipo:'numero'},{key:'horasMes',label:'Horas de uso por mês',tipo:'numero'},{key:'manutencaoMensal',label:'Manutenção mensal (R$)',tipo:'numero'},{key:'observacao',label:'Observação'}]} resultado={m=>`${resultado(C.depreciacaoHora(m))} / hora`}/></TabsContent>
 <TabsContent value="ferramentas"><CadastroCustos titulo="Ferramentas" registros={ferramentas} salvar={setFerramentas} novo={()=>({id:crypto.randomUUID(),nome:'',valorCompra:0,modo:'pecas',vidaUtil:0,ativo:true})} campos={[{key:'nome',label:'Nome'},{key:'valorCompra',label:'Valor de compra (R$)',tipo:'numero'},{key:'dataCompra',label:'Data de compra',tipo:'data'},{key:'modo',label:'Vida útil em',opcoes:[['pecas','Peças produzidas'],['meses','Meses']]},{key:'vidaUtil',label:'Vida útil estimada',tipo:'numero'},{key:'observacao',label:'Observação'}]} resultado={f=>`${resultado(C.desgasteFerramentaPorPeca(f,rateio.produtosMes))} / peça`}/></TabsContent>
 <TabsContent value="indiretos" className="space-y-4"><p className="text-sm text-muted-foreground">Gastos necessários para manter a produção, mas que não pertencem a um produto específico. Não cadastre o mesmo gasto duas vezes.</p><Button asChild variant="outline"><Link to="/precificacao">Editar gastos fixos existentes</Link></Button>{gastos.map(g=><p key={g.id} className="text-sm">{g.nome}: {g.valor?brl(Number(g.valor.replace(',','.'))||0):'Sem valor configurado'}</p>)}<p className="font-semibold">Total mensal: {brl(C.totalIndiretosMensal(indiretos,fixos))}</p><CadastroCustos titulo="Outros custos indiretos" registros={indiretos} salvar={setIndiretos} novo={()=>({id:crypto.randomUUID(),nome:'',categoria:'Outros',valor:0,periodicidade:'mensal',ativo:true})} campos={[{key:'nome',label:'Nome'},{key:'categoria',label:'Categoria',opcoes:C.CATEGORIAS_INDIRETO.map(c=>[c,c])},{key:'valor',label:'Valor (R$)',tipo:'numero'},{key:'periodicidade',label:'Periodicidade',opcoes:[['mensal','Mensal'],['semanal','Semanal'],['anual','Anual']]},{key:'inicio',label:'Início',tipo:'data'},{key:'observacao',label:'Observação'}]} resultado={c=>`${brl(C.valorMensal(c))} / mês`}/></TabsContent>
 <TabsContent value="rateio" className="space-y-5"><p className="text-sm text-muted-foreground">Divida o total mensal pela produção estimada ou pelas horas produtivas. Este rateio substitui o custo fixo antigo, sem somá-lo novamente.</p><div className="flex gap-4">{(['produtos','horas'] as const).map(m=><label key={m} className="flex gap-2"><input type="radio" name="rateio" checked={rateio.metodo===m} onChange={()=>setRateio({...rateio,metodo:m})}/>{m==='produtos'?'Por produto':'Por hora'}</label>)}</div><label className="grid gap-2">Produção estimada por mês<MoneyInput value={rateio.produtosMes} onChange={v=>setRateio({...rateio,produtosMes:v})}/></label><label className="grid gap-2">Horas produtivas por mês<MoneyInput value={rateio.horasMes} onChange={v=>setRateio({...rateio,horasMes:v})}/></label>{!(rateio.metodo==='produtos'?rateio.produtosMes:rateio.horasMes) && <p className="text-warning">Rateio não configurado. Informe a capacidade mensal.</p>}</TabsContent>
 <TabsContent value="desperdício" className="space-y-4"><p className="text-sm text-muted-foreground">Perdas de materiais e embalagens na produção. Não inclui mão de obra nem máquinas. A reserva de imprevistos é separada; não use ambas para cobrir a mesma perda.</p><label className="grid gap-2">Desperdício geral (%)<MoneyInput value={desperdicio.percentual} onChange={v=>setDesperdicio({...desperdicio,percentual:Math.min(v,100)})}/></label>{materiais.map(m=><div key={m.id} className="flex flex-wrap items-center gap-3 border-b border-border py-3"><label className="flex items-center gap-2"><input type="checkbox" checked={desperdicio.porMaterial[m.id]!==undefined} onChange={e=>{const next={...desperdicio.porMaterial};if(e.target.checked)next[m.id]=desperdicio.percentual;else delete next[m.id];setDesperdicio({...desperdicio,porMaterial:next});}}/>{m.nome} · Percentual próprio</label>{desperdicio.porMaterial[m.id]!==undefined && <MoneyInput aria-label={`Desperdício de ${m.nome}`} className="w-24" value={desperdicio.porMaterial[m.id]} onChange={v=>setDesperdicio({...desperdicio,porMaterial:{...desperdicio.porMaterial,[m.id]:Math.min(v,100)}})}/>}</div>)}</TabsContent>
 <TabsContent value="mão de obra" className="space-y-4"><p>Valor da hora: {hora>0?brl(hora):'Sem configuração'}</p><p className="text-sm text-muted-foreground">A mão de obra usa o tempo real de produção de cada item.</p><Button asChild><Link to="/precificacao">Editar dados de trabalho</Link></Button></TabsContent>
 </Tabs></div>;
}
