import { useState } from "react";
import { Plus, Trash2, Pencil, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { MoneyInput } from "@/components/money-input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
export type CampoCusto = { key: string; label: string; tipo?: "numero" | "data"; opcoes?: string[][] };
export function CadastroCustos<T extends {id: string; nome: string; ativo: boolean}>({titulo, registros, salvar, novo, campos, resultado}: {titulo: string; registros: T[]; salvar: (v: T[]) => void; novo: () => T; campos: CampoCusto[]; resultado: (v:T) => string}) {
 const [draft, setDraft] = useState<T | null>(null);
 return <section className="space-y-4"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">{titulo}</h2><Button onClick={()=>setDraft(novo())}><Plus className="size-4"/>Adicionar</Button></div>
 {draft && <form className="space-y-4 border-b border-border pb-5" onSubmit={e=>{e.preventDefault(); if(!draft.nome.trim()) return; const invalid = campos.some(c=>c.tipo==='numero' && (!Number.isFinite(Number((draft as Record<string, unknown>)[c.key])) || Number((draft as Record<string, unknown>)[c.key])<0)); if(invalid){toast.error('Valores precisam ser positivos.');return;} salvar([...registros.filter(r=>r.id!==draft.id),draft]);setDraft(null);}}><div className="grid gap-4 sm:grid-cols-2">{campos.map(c=><label className="grid gap-2 text-sm" key={c.key}>{c.label}{c.opcoes ? <Select value={String((draft as Record<string, unknown>)[c.key] ?? '')} onValueChange={v=>setDraft({...draft,[c.key]:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{c.opcoes.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select> : c.tipo==='numero' ? <MoneyInput value={Number((draft as Record<string, unknown>)[c.key])||0} onChange={v=>setDraft({...draft,[c.key]:v})}/> : <Input required={c.key==='nome'} type={c.tipo==='data'?'date':'text'} value={String((draft as Record<string, unknown>)[c.key] ?? '')} onChange={e=>setDraft({...draft,[c.key]:e.target.value})}/>}</label>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={draft.ativo} onChange={e=>setDraft({...draft,ativo:e.target.checked})}/>Ativo</label><div className="flex gap-2"><Button type="submit"><Save className="size-4"/>Salvar</Button><Button type="button" variant="outline" onClick={()=>setDraft(null)}>Cancelar</Button></div><p className="text-sm text-muted-foreground">{resultado(draft)}</p></form>}
 {!registros.length && <p className="text-muted-foreground">Nenhum cadastro. Sem custo configurado.</p>}
 {registros.map(r=><div key={r.id} className="flex items-center justify-between gap-3 border-b border-border py-3"><div className="min-w-0"><p className="font-medium break-words">{r.nome}{!r.ativo && ' · Inativo'}</p><p className="text-sm text-muted-foreground">{resultado(r)}</p></div><div className="flex shrink-0"><Button variant="ghost" size="icon" aria-label={`Editar ${r.nome}`} onClick={()=>setDraft({...r})}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" aria-label={`Excluir ${r.nome}`} onClick={()=>{if(window.confirm(`Excluir ${r.nome}? Itens que usam este cadastro ficarão com aviso.`)) salvar(registros.filter(x=>x.id!==r.id));}}><Trash2 className="size-4"/></Button></div></div>)}
 </section>;
}
