/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as FaturamentoRouteImport } from './routes/faturamento'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturamentoRoute = FaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ExecutivoRoute: typeof ExecutivoRoute
  FaturamentoRoute: typeof FaturamentoRoute
  InteligenciaRoute: typeof InteligenciaRoute
  MateriaisRoute: typeof MateriaisRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturamento': {
      id: '/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof FaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ExecutivoRoute: ExecutivoRoute,
  FaturamentoRoute: FaturamentoRoute,
  InteligenciaRoute: InteligenciaRoute,
  MateriaisRoute: MateriaisRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
