/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrecificarItemRouteImport } from './routes/precificar-item'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as FaturamentoRouteImport } from './routes/faturamento'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CDataRouteImport } from './routes/c.$data'
import { Route as AssinarSucessoRouteImport } from './routes/assinar.sucesso'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificarItemRoute = PrecificarItemRouteImport.update({
  id: '/precificar-item',
  path: '/precificar-item',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturamentoRoute = FaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CDataRoute = CDataRouteImport.update({
  id: '/c/$data',
  path: '/c/$data',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarSucessoRoute = AssinarSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => AssinarRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/precificar-item': typeof PrecificarItemRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinar/sucesso': typeof AssinarSucessoRoute
  '/c/$data': typeof CDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/precificar-item': typeof PrecificarItemRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinar/sucesso': typeof AssinarSucessoRoute
  '/c/$data': typeof CDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/executivo': typeof ExecutivoRoute
  '/faturamento': typeof FaturamentoRoute
  '/inteligencia': typeof InteligenciaRoute
  '/materiais': typeof MateriaisRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pedidos': typeof PedidosRoute
  '/perfil': typeof PerfilRoute
  '/precificacao': typeof PrecificacaoRoute
  '/precificar-item': typeof PrecificarItemRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assinar/sucesso': typeof AssinarSucessoRoute
  '/c/$data': typeof CDataRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/orcamentos'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/precificar-item'
    | '/produtos'
    | '/reset-password'
    | '/assinar/sucesso'
    | '/c/$data'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/orcamentos'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/precificar-item'
    | '/produtos'
    | '/reset-password'
    | '/assinar/sucesso'
    | '/c/$data'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/assinar'
    | '/auth'
    | '/catalogo'
    | '/configuracoes'
    | '/executivo'
    | '/faturamento'
    | '/inteligencia'
    | '/materiais'
    | '/orcamentos'
    | '/pedidos'
    | '/perfil'
    | '/precificacao'
    | '/precificar-item'
    | '/produtos'
    | '/reset-password'
    | '/assinar/sucesso'
    | '/c/$data'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRoute: typeof AssinarRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ExecutivoRoute: typeof ExecutivoRoute
  FaturamentoRoute: typeof FaturamentoRoute
  InteligenciaRoute: typeof InteligenciaRoute
  MateriaisRoute: typeof MateriaisRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PedidosRoute: typeof PedidosRoute
  PerfilRoute: typeof PerfilRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  PrecificarItemRoute: typeof PrecificarItemRoute
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CDataRoute: typeof CDataRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificar-item': {
      id: '/precificar-item'
      path: '/precificar-item'
      fullPath: '/precificar-item'
      preLoaderRoute: typeof PrecificarItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturamento': {
      id: '/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof FaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$data': {
      id: '/c/$data'
      path: '/c/$data'
      fullPath: '/c/$data'
      preLoaderRoute: typeof CDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/sucesso': {
      id: '/assinar/sucesso'
      path: '/sucesso'
      fullPath: '/assinar/sucesso'
      preLoaderRoute: typeof AssinarSucessoRouteImport
      parentRoute: typeof AssinarRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssinarRouteChildren {
  AssinarSucessoRoute: typeof AssinarSucessoRoute
}

const AssinarRouteChildren: AssinarRouteChildren = {
  AssinarSucessoRoute: AssinarSucessoRoute,
}

const AssinarRouteWithChildren =
  AssinarRoute._addFileChildren(AssinarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRoute: AssinarRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ExecutivoRoute: ExecutivoRoute,
  FaturamentoRoute: FaturamentoRoute,
  InteligenciaRoute: InteligenciaRoute,
  MateriaisRoute: MateriaisRoute,
  OrcamentosRoute: OrcamentosRoute,
  PedidosRoute: PedidosRoute,
  PerfilRoute: PerfilRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  PrecificarItemRoute: PrecificarItemRoute,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CDataRoute: CDataRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
